<?php

namespace Bonton\Japi;

const GET_RESOURCES = 1;
const GET_RESOURCE = 2;
const GET_RESOURCE_RELATIONSHIP = 3;
const GET_RELATED_RESOURCE = 4;
const CREATE_RESOURCE = 5;
const CREATE_RESOURCE_RELATIONSHIP = 6;
const UPDATE_RESOURCE = 7;
const UPDATE_RESOURCE_RELATIONSHIP = 8;
const DELETE_RESOURCE = 9;
const DELETE_RESOURCE_RELATIONSHIP = 10;